#!/bin/bash
# Jalankan script ini SEKALI di server kamu untuk membuat file .env
# Usage: bash setup-env.sh

cat > .env << 'EOF'
BOT_TOKEN=8194599694:AAGx9dRZMFER1n4hixHRIdR3e7x8V9hQ9dU
BOT_NAME=Panel Bot
BOT_VERSION=1.0.0
OWNER_USERNAME=zeetasi
OWNER_IDS=7338916279

PANEL_URL=https://panelll.zeetasi.qzz.io
PTERO_APP_KEY=ptla_fxEuG8nZjZZoIpdjJZAVmGjJ9XR42DdUyhpURItUAgi
PTERO_CLIENT_KEY=ptlc_6kQZyLDMG1VD6o0d5RGsSzRwjbyWUr9Pq8VJEmv5d9d
DEFAULT_LOCATION_ID=1
DEFAULT_NODE_ID=1

MAX_PANEL_PER_USER=1
MAX_PANEL_PREMIUM=3
CLAIM_COOLDOWN=8640000
REDEEM_COOLDOWN=3600

REQUIRED_GROUP_COUNT=2
REQUIRED_SHARE_COUNT=3

REFERRAL_POINTS=10
REFERRAL_PREMIUM_THRESHOLD=50
REFERRAL_VOUCHER_THRESHOLD=30

LOG_GROUP_ID=

RATE_LIMIT_WINDOW=60
RATE_LIMIT_MAX=20
RATE_LIMIT_WARNINGS=3

AUTO_BACKUP=false
AUTO_SECURITY=false
AUTO_BLACKLIST=false
EOF

echo "✅ File .env berhasil dibuat!"
echo "Sekarang jalankan: npm install && node index.js"
